apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: ticketing-app
build:
  local:
    push: false
  artifacts:
    - image: kandy0511/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'auth/**/*.ts'
            dest: .
    - image: kandy0511/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'tickets/**/*.ts'
            dest: .
manifests:
  rawYaml:
    - infra/k8s/*.yaml
deploy:
  kubectl: {}